### Get all users
GET http://localhost:3000/api/users

### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Alicez",
  "email": "alice@exampless.com",
  "age": 30
}

### Delete a user
DELETE http://localhost:3000/api/users?id=1
